### ISSUE TITLE
Implementation & style

### ISSUE THREAD

**Issue by Suntrie** [uncleanw/tic_tac_toe#4]
1. В названии пакетов лучше придерживаться стандартной конвенции, например, [такой]( https://google.github.io/styleguide/javaguide.html). Тесты обычно кидают в пакет с таким же названием, что и основной код (для тестирования package-private элементов);

2. Объявлять элементы перечисления Symbols, коль скоро Вы не используете конструктор, можно несколько [проще](https://docs.oracle.com/javase/tutorial/java/javaOO/enum.html);

3. Не вполне понятно, почему не final size вдруг стала публичной (со всеми уязвимостями публичных переменных). Почему она статическая (общая для всех объектов класса) - тоже не очень ясно;

4. Ряд методов - типа findForAdd - относятся к методам реализации. Такие должны быть "зашиты" внутрь Вашего класса и наружу торчать не должны (должны быть private). Бонус:  тестировать их в явном виде, как правило, тоже не надо;

5. В addSymbol завелась, вроде бы, ничем не мотивированная копипаста;

6. clear, по-хорошему, вполне может вернуть false - и неплохо бы позволять ему это сделать;

7. Поправьте меня, пожалуйста, но, КМК, в findMaxLine

` while (liteTester(height, width)) {
            while (getCell(height, width) != Symbols.Error)` 

  - условие останова будет выполняться  
  или не выполняться одновременно (непонятно, зачем их 2). В clearAll вроде тоже можно проще;

8. Если я правильно поняла Ваш вопрос в комментарии под Line - то да, так можно.

**Comment by uncleanw** [comment]
2) сделал чуть-чуть иначе, тк они Symbols объявляется в другом файле и идея сказала, что `this.symbol = symbol` мне не нужен
